# Generated by Django 3.0.6 on 2020-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_credit_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_cards',
            name='balance',
            field=models.FloatField(default=5000),
        ),
    ]
