# Generated by Django 3.0.6 on 2020-07-28 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_user_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_primary_image', models.ImageField(upload_to='products')),
                ('product_secondary_image_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_secondary_image_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_secondary_image_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_name', models.CharField(max_length=100)),
                ('product_tag_line', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
