# Generated by Django 3.0.6 on 2020-07-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField()),
                ('total_bill', models.FloatField()),
                ('dateTime', models.DateTimeField(default='2020-07-30 01:06:24')),
                ('order_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_this_is_buyer', to=settings.AUTH_USER_MODEL)),
                ('order_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_this_is_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product_reviews',
            name='date',
            field=models.DateField(default='2020-07-30'),
        ),
        migrations.CreateModel(
            name='order_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.products')),
            ],
        ),
    ]
