# Generated by Django 3.0.6 on 2020-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200730_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(default='2020-07-30 03:06:28'),
        ),
    ]
