# Generated by Django 3.0.6 on 2020-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200730_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isCompleted',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(default='2020-07-30 04:00:30'),
        ),
    ]
