# Generated by Django 3.0.6 on 2020-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200730_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(default='2020-08-03 00:49:37'),
        ),
        migrations.AlterField(
            model_name='product_reviews',
            name='date',
            field=models.DateField(default='2020-08-03'),
        ),
    ]
